name: good_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.5
  faker: ^2.0.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^6.0.0
  logger: ^1.1.0
  mocktail: ^0.3.0

dev_dependencies:
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fixtures/
    - assets/images/
    - assets/images/logo/

flutter_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo/logo_square.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/logo/logo_square.png"
    background_color: "#FFCC00"
    theme_color: "#FFCC00"
  windows:
    generate: true
    image_path: "assets/images/logo/logo_square.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/logo/logo_square.png"
