name: good_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.5
  faker: ^2.1.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.18
  flutter_secure_storage: ^8.0.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  injectable: ^2.1.0
  json_annotation: ^4.8.0
  logger: ^1.2.2

dev_dependencies:
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.12.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  injectable_generator: ^2.1.4
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  test: any

dependency_overrides:
  test_api: 0.4.17

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fixtures/
    - assets/images/
    - assets/images/logo/

flutter_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo/logo_square.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/logo/logo_square.png"
    background_color: "#FFCC00"
    theme_color: "#FFCC00"
  windows:
    generate: true
    image_path: "assets/images/logo/logo_square.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/logo/logo_square.png"
